name: Tests

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check changes
    outputs:
      src: ${{ steps.filter.outputs.src }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Add filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'app/**'
              - 'routes/**'
              - 'tests/**'
              - '.github/**'

  testing:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: composer test
