name: Check & fix styling

on:
  push:
    branches: [ todo_fix_this ]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Install Dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Run PHP CS Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --config=.php-cs-fixer.dist.php

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Fix styling
